# Generated by Django 6.0.3 on 2026-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecePoisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=100)),
                ('nom_latin', models.CharField(blank=True, max_length=150)),
                ('categorie', models.CharField(choices=[('pelagique', 'Pélagique'), ('demersal', 'Démersal'), ('crustace', 'Crustacé'), ('mollusque', 'Mollusque')], max_length=20)),
                ('taille_min_cm', models.FloatField(blank=True, help_text='Taille légale minimale de capture en cm', null=True)),
                ('poids_min_kg', models.FloatField(blank=True, null=True)),
                ('is_protege', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Espèce de poisson',
                'verbose_name_plural': 'Espèces de poissons',
            },
        ),
    ]
