# Generated by Django 6.0.3 on 2026-03-10 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('captures', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_gps', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('quantite_kg', models.FloatField()),
                ('engin_peche', models.CharField(blank=True, choices=[('filet', 'Filet'), ('ligne', 'Ligne'), ('chalut', 'Chalut'), ('nasse', 'Nasse'), ('harpon', 'Harpon'), ('autre', 'Autre')], max_length=20)),
                ('date_capture', models.DateTimeField()),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('bateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bateau')),
                ('espece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='captures.especepoisson')),
                ('pecheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='accounts.pecheur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures_validees', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='zones.zonepeche')),
            ],
            options={
                'verbose_name': 'Déclaration de capture',
                'verbose_name_plural': 'Déclarations de captures',
                'ordering': ['-date_capture'],
            },
        ),
    ]
