# Generated by Django 6.0.3 on 2026-03-10 18:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('zone_interdite', 'Entrée en zone interdite'), ('peche_illegale', 'Pêche illégale signalée'), ('surexploitation', 'Surexploitation détectée'), ('meteo', 'Alerte météo'), ('autre', 'Autre')], max_length=25)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='warning', max_length=10)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_traitement', 'En traitement'), ('resolue', 'Résolue')], default='ouverte', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_signalees', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='zones.zonepeche')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
