# Generated by Django 6.0.3 on 2026-03-10 13:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrajetPeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trajet', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('date_depart', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('is_suspect', models.BooleanField(default=False, help_text='True si le trajet passe par une zone interdite')),
                ('notes', models.TextField(blank=True)),
                ('bateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bateau')),
                ('pecheur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='accounts.pecheur')),
            ],
            options={
                'verbose_name': 'Trajet de pêche',
                'verbose_name_plural': 'Trajets de pêche',
                'ordering': ['-date_depart'],
            },
        ),
    ]
