# Generated by Django 6.0.3 on 2026-03-10 13:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePeche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_zone', models.CharField(choices=[('autorisee', 'Zone Autorisée'), ('interdite', 'Zone Interdite'), ('protegee', 'Aire Protégée'), ('surveillance', 'Zone de Surveillance')], max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('en_revision', 'En révision')], default='active', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('superficie_km2', models.FloatField(blank=True, null=True)),
                ('profondeur_min', models.FloatField(blank=True, help_text='En mètres', null=True)),
                ('profondeur_max', models.FloatField(blank=True, help_text='En mètres', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_creees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone de pêche',
                'verbose_name_plural': 'Zones de pêche',
                'ordering': ['-date_creation'],
            },
        ),
    ]
